apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: open-sauced
  title: Open Sauced
  description: Open Sauced Description
  tags:
    - nodejs
  annotations:
    github.com/project-slug: ivamuno-backstage/open-sauced
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  providesApis:
    - open-sauced
    - open-sauced-events

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: open-sauced
  description: Open Sauced API
  tags:
    - rest
  links:
    - url: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml
      title: Source spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: team-a
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: open-sauced-events
  description: Open Sauced events
  tags:
    - kafka
  links:
    - url: https://github.com/asyncapi/spec/blob/master/examples/streetlights-kafka.yml
      title: Source spec
      icon: code
spec:
  type: asyncapi
  lifecycle: experimental
  owner: team-a
  definition:
    $text: https://github.com/asyncapi/spec/blob/master/examples/streetlights-kafka.yml
