apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: open-sauced
  title: Open Sauced
  description: Open Sauced Description
  tags:
    - nodejs
  annotations:
    backstage.io/adr-location: ./docs/adrs
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ivamuno-backstage/open-sauced
    sonarqube.org/project-key: ivamuno-backstage/ivamuno-backstage_open-sauced
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/backlog
      title: Backlog Tool
      icon: dashboard
    - url: https://example.com/help
      title: Incident Tool
      icon: help
    - url: https://example.com/metrics
      title: Metrics Tool
      icon: web
    - url: https://example.com/alert
      title: Alert Tool
      icon: alert
    - url: https://example.com/logging
      title: Logging Tool
      icon: help
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  providesApis:
    - open-sauced
    - open-sauced-events

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: open-sauced-consumer
  title: Open Sauced consumer
  description: Open Sauced consumer
  tags:
    - nodejs
  annotations:
    github.com/project-slug: ivamuno-backstage/open-sauced
  links: []
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  consumesApis:
    - open-sauced-events

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: open-sauced
  title: Open Sauced API
  description: Open Sauced API
  tags:
    - rest
  links:
    - url: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml
      title: Source spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: team-a
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: open-sauced-events
  title: Open Sauced events
  description: Open Sauced events
  tags:
    - kafka
  links:
    - url: https://github.com/asyncapi/spec/blob/master/examples/streetlights-kafka.yml
      title: Source spec
      icon: code
spec:
  type: asyncapi
  lifecycle: experimental
  owner: team-a
  definition:
    $text: https://github.com/asyncapi/spec/blob/master/examples/streetlights-kafka.yml
