apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: open-sauced
  annotations:
    github.com/project-slug: ivamuno-backstage/open-sauced
spec:
  type: other
  lifecycle: unknown
  owner: team-a
